version: '3'

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: pauloch8/nginx:prod
    networks:
      - node-network
    ports:
      - "8080:80"




  app:
    container_name: app
    build: 
      context: ./node
      dockerfile: Dockerfile.dev
    image: pauloch8/node-dev
    networks:
      - node-network
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./node:/app


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    

networks:
  node-network:
    driver: bridge