version: '3'

services:

  nginx:
    container_name: nginx
    build: 
      context: ./nginx
    image: pauloch8/nginx
    networks:
      - node-network
    ports:
      - "8080:80"

  app:
    container_name: app
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    

networks:
  node-network:
    driver: bridge