version: '3'

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: pauloch8/nginx:prod
    entrypoint: dockerize -wait http://app:3000 -timeout 50s nginx -g "daemon off;"
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    container_name: app
    build: 
      context: node
      dockerfile: Dockerfile.prod
    image: pauloch8/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node /usr/src/app/index.js
    networks:
      - node-network
    tty: true
    depends_on:
      - db
    

    


  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    

networks:
  node-network:
    driver: bridge