version: '3'

services:

  nginx:
    entrypoint: dockerize -wait http://app:3000 -timeout 50s nginx -g "daemon off;"
    depends_on:
      - app

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    image: pauloch8/node:prod
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node /app/src/index.js