version: '3'

services:

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.dev
    image: pauloch8/node:dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./node:/app