FROM node:15 AS build

WORKDIR /app

COPY package*.json .

RUN npm install --production

FROM node:15-slim

WORKDIR /app

COPY ./dockerize-linux-amd64-v0.6.1.tar.gz .
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz \
    && rm dockerize-linux-amd64-v0.6.1.tar.gz

COPY src ./src

COPY --from=build /app/node_modules ./node_modules

EXPOSE 3000

CMD [ "npm", "start" ]